import db from "./db.js";
import { v4 as uuidv4 } from "uuid";

const seminars = [
  {
    title: "International Aikido Seminar",
    instructor: "Yamada Yoshimitsu",
    instructorRank: "8th Dan",
    organization: "USAF",
    style: "Aikikai",
    startDate: "2026-03-15",
    endDate: "2026-03-17",
    venue: "New York Aikikai",
    city: "New York",
    country: "United States",
    countryCode: "US",
    latitude: 40.7128,
    longitude: -74.006,
    description:
      "Annual spring seminar led by Yamada Sensei. Open to all levels.",
    level: "all",
    fee: "$150",
    source: "usaf",
    sourceUrl: "https://services.usaikifed.com/events/",
    registrationUrl: "https://services.usaikifed.com/events/",
  },
  {
    title: "Hombu Dojo Spring Gasshuku",
    instructor: "Ueshiba Mitsuteru",
    instructorRank: "Doshu",
    organization: "Aikikai",
    style: "Aikikai",
    startDate: "2026-04-05",
    endDate: "2026-04-07",
    venue: "Aikikai Hombu Dojo",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    latitude: 35.6998,
    longitude: 139.7189,
    description: "Spring intensive training at Aikido world headquarters.",
    level: "intermediate",
    fee: "¥15,000",
    source: "aikikai",
    sourceUrl: "https://aikikai.or.jp/eng/",
    registrationUrl: "https://aikikai.or.jp/eng/",
  },
  {
    title: "European Aikido Congress",
    instructor: "Christian Tissier",
    instructorRank: "8th Dan",
    organization: "FFAB",
    style: "Aikikai",
    startDate: "2026-05-10",
    endDate: "2026-05-12",
    venue: "Palais des Sports",
    city: "Paris",
    country: "France",
    countryCode: "FR",
    latitude: 48.8566,
    longitude: 2.3522,
    description:
      "Annual European congress featuring demonstrations and intensive classes.",
    level: "all",
    fee: "€120",
    source: "aikidotravel",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Summer School of Aikido",
    instructor: "Endo Seishiro",
    instructorRank: "8th Dan",
    organization: "Aikikai",
    style: "Aikikai",
    startDate: "2026-07-20",
    endDate: "2026-07-26",
    venue: "Katsuura Seminar House",
    city: "Katsuura",
    country: "Japan",
    countryCode: "JP",
    latitude: 35.1328,
    longitude: 140.3018,
    description: "Week-long summer intensive focusing on fluid movement.",
    level: "intermediate",
    fee: "¥30,000",
    source: "aikikai",
    sourceUrl: "https://aikikai.or.jp/eng/",
    registrationUrl: "https://aikikai.or.jp/eng/",
  },
  {
    title: "British Aikido Federation National Course",
    instructor: "Kanetsuka Minoru",
    instructorRank: "7th Dan",
    organization: "BAF",
    style: "Aikikai",
    startDate: "2026-06-14",
    endDate: "2026-06-15",
    venue: "Crystal Palace National Sports Centre",
    city: "London",
    country: "United Kingdom",
    countryCode: "GB",
    latitude: 51.4189,
    longitude: -0.0706,
    description: "National course open to all BAF members and visitors.",
    level: "all",
    fee: "£45",
    source: "iaf",
    sourceUrl: "https://aikido-international.org/events/",
    registrationUrl: "https://aikido-international.org/events/",
  },
  {
    title: "Aikido Down Under Seminar",
    instructor: "Sugano Seiichi Memorial",
    instructorRank: "8th Dan",
    organization: "AAA",
    style: "Aikikai",
    startDate: "2026-08-01",
    endDate: "2026-08-03",
    venue: "Sydney Aikido Centre",
    city: "Sydney",
    country: "Australia",
    countryCode: "AU",
    latitude: -33.8688,
    longitude: 151.2093,
    description:
      "Memorial seminar celebrating the legacy of Sugano Sensei in Australia.",
    level: "all",
    fee: "AUD 120",
    source: "aikidotravel",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Berlin Aikido Intensive",
    instructor: "Asai Katsuaki",
    instructorRank: "7th Dan",
    organization: "DAB",
    style: "Aikikai",
    startDate: "2026-04-18",
    endDate: "2026-04-20",
    venue: "Sportforum Berlin",
    city: "Berlin",
    country: "Germany",
    countryCode: "DE",
    latitude: 52.52,
    longitude: 13.405,
    description: "Three-day intensive seminar with focus on weapons techniques.",
    level: "intermediate",
    fee: "€80",
    source: "european-af",
    sourceUrl: "https://aikido-eu.org",
    registrationUrl: "https://aikido-eu.org",
  },
  {
    title: "Yoshinkan Aikido International Seminar",
    instructor: "Payet Jacques",
    instructorRank: "7th Dan",
    organization: "Yoshinkan",
    style: "Yoshinkan",
    startDate: "2026-09-10",
    endDate: "2026-09-14",
    venue: "Yoshinkan Honbu Dojo",
    city: "Tokyo",
    country: "Japan",
    countryCode: "JP",
    latitude: 35.7076,
    longitude: 139.7514,
    description:
      "International gathering of Yoshinkan practitioners for intensive training.",
    level: "advanced",
    fee: "¥25,000",
    source: "manual",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Midwest Aikido Summer Camp",
    instructor: "Ikeda Hiroshi",
    instructorRank: "7th Dan",
    organization: "USAF",
    style: "Aikikai",
    startDate: "2026-06-28",
    endDate: "2026-07-04",
    venue: "Camp Hayo-Went-Ha",
    city: "Central Lake",
    country: "United States",
    countryCode: "US",
    latitude: 44.8562,
    longitude: -85.243,
    description:
      "Annual week-long summer camp combining Aikido practice with outdoor activities.",
    level: "all",
    fee: "$450",
    source: "usaf",
    sourceUrl: "https://services.usaikifed.com/events/",
    registrationUrl: "https://services.usaikifed.com/events/",
  },
  {
    title: "Scandinavian Aikido Federation Congress",
    instructor: "Fujita Masatake",
    instructorRank: "6th Dan",
    organization: "SAF",
    style: "Aikikai",
    startDate: "2026-05-23",
    endDate: "2026-05-25",
    venue: "Eriksdalsbadet",
    city: "Stockholm",
    country: "Sweden",
    countryCode: "SE",
    latitude: 59.3072,
    longitude: 18.0678,
    description: "Annual congress for Scandinavian Aikido practitioners.",
    level: "all",
    fee: "SEK 800",
    source: "european-af",
    sourceUrl: "https://aikido-eu.org",
    registrationUrl: "https://aikido-eu.org",
  },
  {
    title: "Aikido e Harmonia",
    instructor: "Yamashima Takeshi",
    instructorRank: "6th Dan",
    organization: "FIPA",
    style: "Aikikai",
    startDate: "2026-10-03",
    endDate: "2026-10-05",
    venue: "Pavilhão Municipal",
    city: "Lisbon",
    country: "Portugal",
    countryCode: "PT",
    latitude: 38.7223,
    longitude: -9.1393,
    description:
      "Aikido seminar exploring the connection between harmony and martial arts.",
    level: "beginner",
    fee: "€60",
    source: "aikidotravel",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Canadian Aikido Federation Summer Seminar",
    instructor: "Kawahara Yukio Memorial",
    instructorRank: "8th Dan",
    organization: "CAF",
    style: "Aikikai",
    startDate: "2026-08-15",
    endDate: "2026-08-17",
    venue: "University of Alberta Gym",
    city: "Edmonton",
    country: "Canada",
    countryCode: "CA",
    latitude: 53.5461,
    longitude: -113.4938,
    description:
      "Annual summer seminar honoring the legacy of Kawahara Sensei.",
    level: "all",
    fee: "CAD 100",
    source: "aikiweb",
    sourceUrl: "https://aikiweb.com/seminars/",
    registrationUrl: "https://aikiweb.com/seminars/",
  },
  {
    title: "Shodokan Aikido World Tournament",
    instructor: "Nariyama Tetsuro",
    instructorRank: "8th Dan",
    organization: "SAF",
    style: "Shodokan",
    startDate: "2026-11-01",
    endDate: "2026-11-03",
    venue: "Osaka Prefectural Gymnasium",
    city: "Osaka",
    country: "Japan",
    countryCode: "JP",
    latitude: 34.6937,
    longitude: 135.5023,
    description: "Biennial world tournament and seminar for Shodokan Aikido.",
    level: "advanced",
    fee: "¥10,000",
    source: "manual",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Aikido South Africa National Seminar",
    instructor: "Andrew Williamson",
    instructorRank: "5th Dan",
    organization: "ASA",
    style: "Aikikai",
    startDate: "2026-09-20",
    endDate: "2026-09-21",
    venue: "Ellis Park Arena",
    city: "Johannesburg",
    country: "South Africa",
    countryCode: "ZA",
    latitude: -26.2041,
    longitude: 28.0473,
    description:
      "National seminar bringing together Aikido practitioners from across South Africa.",
    level: "all",
    fee: "ZAR 500",
    source: "aikidotravel",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "Aikido of Eurasia Open Seminar",
    instructor: "Mikhail Ryabko",
    instructorRank: "5th Dan",
    organization: "EAF",
    style: "Aikikai",
    startDate: "2026-06-07",
    endDate: "2026-06-08",
    venue: "Moscow Sports Palace",
    city: "Moscow",
    country: "Russia",
    countryCode: "RU",
    latitude: 55.7558,
    longitude: 37.6173,
    description: "Open seminar welcoming practitioners from Eurasia and beyond.",
    level: "all",
    fee: "RUB 3,000",
    source: "eurasia-aikido",
    sourceUrl: "https://eurasiaaikido.org/aikido-calendar/",
    registrationUrl: "https://eurasiaaikido.org/aikido-calendar/",
  },
  {
    title: "Aikido Italia Summer Camp",
    instructor: "Fujimoto Yoji",
    instructorRank: "7th Dan",
    organization: "Aikikai d'Italia",
    style: "Aikikai",
    startDate: "2026-07-05",
    endDate: "2026-07-12",
    venue: "Centro Sportivo Coverciano",
    city: "Florence",
    country: "Italy",
    countryCode: "IT",
    latitude: 43.7696,
    longitude: 11.2558,
    description:
      "Week-long summer camp in the beautiful Tuscan countryside.",
    level: "all",
    fee: "€200",
    source: "european-af",
    sourceUrl: "https://aikido-eu.org",
    registrationUrl: "https://aikido-eu.org",
  },
  {
    title: "Beginners Welcome Workshop",
    instructor: "Patricia Hendricks",
    instructorRank: "6th Dan",
    organization: "USAF",
    style: "Aikikai",
    startDate: "2026-03-28",
    endDate: "2026-03-29",
    venue: "Aikido of Berkeley",
    city: "Berkeley",
    country: "United States",
    countryCode: "US",
    latitude: 37.8716,
    longitude: -122.2727,
    description: "Special workshop designed to introduce newcomers to Aikido.",
    level: "beginner",
    fee: "$60",
    source: "aikiweb",
    sourceUrl: "https://aikiweb.com/seminars/",
    registrationUrl: "https://aikiweb.com/seminars/",
  },
  {
    title: "Asia-Pacific Aikido Friendship Seminar",
    instructor: "Seki Shoji",
    instructorRank: "7th Dan",
    organization: "Aikikai",
    style: "Aikikai",
    startDate: "2026-10-18",
    endDate: "2026-10-20",
    venue: "Kuala Lumpur Convention Centre",
    city: "Kuala Lumpur",
    country: "Malaysia",
    countryCode: "MY",
    latitude: 3.1569,
    longitude: 101.7123,
    description:
      "Regional seminar promoting Aikido friendship across the Asia-Pacific.",
    level: "all",
    fee: "MYR 200",
    source: "iaf",
    sourceUrl: "https://aikido-international.org/events/",
    registrationUrl: "https://aikido-international.org/events/",
  },
  {
    title: "Aiki Expo Latin America",
    instructor: "Wagner Bull",
    instructorRank: "6th Dan",
    organization: "FLAB",
    style: "Aikikai",
    startDate: "2026-11-14",
    endDate: "2026-11-16",
    venue: "Ginásio Ibirapuera",
    city: "São Paulo",
    country: "Brazil",
    countryCode: "BR",
    latitude: -23.5505,
    longitude: -46.6333,
    description:
      "Cross-style Aikido exposition featuring instructors from across Latin America.",
    level: "all",
    fee: "BRL 250",
    source: "aikidotravel",
    sourceUrl: "https://aikidotravel.com",
    registrationUrl: "https://aikidotravel.com",
  },
  {
    title: "New Zealand Aikido Federation Winter School",
    instructor: "Takase Toshikazu",
    instructorRank: "6th Dan",
    organization: "NZAF",
    style: "Aikikai",
    startDate: "2026-07-18",
    endDate: "2026-07-20",
    venue: "ASB Sports Centre",
    city: "Wellington",
    country: "New Zealand",
    countryCode: "NZ",
    latitude: -41.2866,
    longitude: 174.7756,
    description: "Annual winter school for New Zealand practitioners.",
    level: "all",
    fee: "NZD 120",
    source: "iaf",
    sourceUrl: "https://aikido-international.org/events/",
    registrationUrl: "https://aikido-international.org/events/",
  },
];

// Clear only non-manual (seeded) entries; preserve manually added seminars
db.exec("DELETE FROM seminars WHERE manualOverride = 0");

const insert = db.prepare(`
  INSERT INTO seminars (
    id, title, instructor, instructorRank, organization, style,
    startDate, endDate, venue, city, country, countryCode,
    latitude, longitude, description, level, registrationUrl,
    contactEmail, fee, source, sourceUrl, lastScraped, manualOverride
  ) VALUES (
    @id, @title, @instructor, @instructorRank, @organization, @style,
    @startDate, @endDate, @venue, @city, @country, @countryCode,
    @latitude, @longitude, @description, @level, @registrationUrl,
    @contactEmail, @fee, @source, @sourceUrl, @lastScraped, @manualOverride
  )
`);

const now = new Date().toISOString();

const insertAll = db.transaction(() => {
  for (const s of seminars) {
    insert.run({
      id: uuidv4(),
      title: s.title,
      instructor: s.instructor,
      instructorRank: s.instructorRank ?? null,
      organization: s.organization ?? null,
      style: s.style ?? null,
      startDate: s.startDate,
      endDate: s.endDate,
      venue: s.venue ?? null,
      city: s.city,
      country: s.country,
      countryCode: s.countryCode,
      latitude: s.latitude,
      longitude: s.longitude,
      description: s.description ?? null,
      level: s.level ?? null,
      registrationUrl: s.registrationUrl ?? null,
      contactEmail: null,
      fee: s.fee ?? null,
      source: s.source,
      sourceUrl: s.sourceUrl ?? null,
      lastScraped: now,
      manualOverride: 0,
    });
  }
});

insertAll();
console.log(`Seeded ${seminars.length} seminars.`);
